### PR TITLE
transit support

### PR DESCRIPTION
**Pull request by brandonros**
see https://github.com/kr1sp1n/node-vault/issues/73

### CODE REVIEW

**Review by eheikes — CHANGES_REQUESTED** [review]
A `package-lock.json` is not required (and is actually discouraged by npm) if there is a `yarn.lock`.

**Review by eheikes — APPROVED** [review]

**Comment by eheikes** [comment]
Oh shoot -- we should probably add some unit tests too.

**Comment by brandonros** [comment]
image

These are the unit tests that currently exist for this repo that we are inheriting. Since all I'm doing is adding commands, we should be covered by `generateFunction`

I was going to focus on writing the unit + integration tests for our `node-vault` library that we consume. What do you think?

**Comment by eheikes** [comment]
> These are the unit tests that currently exist for this repo that we are inheriting. Since all I'm doing is adding commands, we should be covered by `generateFunction`
> 
> I was going to focus on writing the unit + integration tests for our `node-vault` library that we consume. What do you think?

Sounds good. I wasn't sure if the existing test suite covered the config automatically.

**Pull request merged**
